---
title: "final-project"
author: "Viren Patel"
date: "4/18/2020"
output: html_document
---
### https://github.com/CSSEGISandData/COVID-19 ###
### https://www.ecdc.europa.eu/en/geographical-distribution-2019-ncov-cases ###
### https://github.com/nytimes/covid-19-data ##

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!require(magrittr)) install.packages("magrittr", repos = "http://cran.us.r-project.org")
if(!require(rvest)) install.packages("rvest", repos = "http://cran.us.r-project.org")
if(!require(readxl)) install.packages("readxl", repos = "http://cran.us.r-project.org")
if(!require(dplyr)) install.packages("dplyr", repos = "http://cran.us.r-project.org")
if(!require(maps)) install.packages("maps", repos = "http://cran.us.r-project.org")
if(!require(ggplot2)) install.packages("ggplot2", repos = "http://cran.us.r-project.org")
if(!require(reshape2)) install.packages("reshape2", repos = "http://cran.us.r-project.org")
if(!require(ggiraph)) install.packages("ggiraph", repos = "http://cran.us.r-project.org")
if(!require(RColorBrewer)) install.packages("RColorBrewer", repos = "http://cran.us.r-project.org")
if(!require(leaflet)) install.packages("leaflet", repos = "http://cran.us.r-project.org")
if(!require(plotly)) install.packages("plotly", repos = "http://cran.us.r-project.org")
if(!require(geojsonio)) install.packages("geojsonio", repos = "http://cran.us.r-project.org")
if(!require(shiny)) install.packages("shiny", repos = "http://cran.us.r-project.org")
if(!require(shinyWidgets)) install.packages("shinyWidgets", repos = "http://cran.us.r-project.org")
if(!require(shinydashboard)) install.packages("shinydashboard", repos = "http://cran.us.r-project.org")
if(!require(shinythemes)) install.packages("shinythemes", repos = "http://cran.us.r-project.org")
if(!require(choroplethr)) install.packages("choroplethr", repos = "http://cran.us.r-project.org")
```

```{r importdata, echo=FALSE}
covid19_us_states = read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
#covid19_us_counties = read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")
covid19_cases = read.csv("source/coronavirus.csv")
worldcountry = geojson_read("source/countries.geo.json", what = "sp")
usstates = geojson_read("source/us-states.geo.json", what = "sp")
states = geojson_read("source/us-states.geo.json", what = "sp")
country_geoms = read.csv("source/country_geoms.csv")
sars_cases = read.csv("source/sars.csv")
countries = read.csv("source/countries_codes_and_coordinates.csv")
ebola_cases = read.csv("source/ebola.csv")
h1n1_cases = read.csv("source/h1n1.csv")
```

```{r attributes, echo=FALSE}
# set mapping colour for each outbreak
cv19_color = "#ff0000"
cv19_other_color = "#ff4500"
sars_color = "#EB9605"
h1n1_color = "#883000"
ebola_color = "#FF7417"
```

```{r map-functions, echo=FALSE}
# function to plot new cases by region
country_region_cases_plot = function(covid19_cases, start_point=c("Date", "Day of 100th confirmed case", "Day of 10th death")) {
                      if (start_point=="Date") {
                        
                        g = ggplot(covid19_cases, 
                                   aes(x = date, 
                                       y = new_outcome, 
                                       fill = region, 
                                       text = paste0(format(date, "%d %B %Y"), "\n", region, ": ",new_outcome))) + 
                             xlim(c(cv_min_date,current_date+1)) +
                             xlab("Date")
                      }
  
                      if (start_point=="Day of 100th confirmed case") {
                        covid19_cases = subset(covid19_cases, days_since_case100>0)
                        
                        g = ggplot(covid19_cases, 
                                   aes(x = days_since_case100, 
                                       y = new_outcome, 
                                       fill = region, 
                                       text = paste0("Day ",days_since_case100, "\n", region, ": ",new_outcome))) +
                            xlab("Days since 100th confirmed case")
                      }
  
                      if (start_point=="Day of 10th death") {
                        covid19_cases = subset(covid19_cases, days_since_death10>0)
                        
                        g = ggplot(covid19_cases, 
                                   aes(x = days_since_death10, 
                                       y = new_outcome, 
                                       fill = region, 
                                       text = paste0("Day ",days_since_death10, "\n", region, ": ",new_outcome))) +
                            xlab("Days since 10th death")
                      }
  
  g1 = g +
        geom_bar(position="stack", stat="identity") + 
        ylab("new") + 
        theme_bw() + 
        scale_fill_manual(values=country_cols) +
        theme(legend.title = element_blank(), 
              legend.position = "", 
              plot.title = element_text(size=10))
  
  ggplotly(g1, tooltip = c("text")) %>% 
            layout(legend = list(font = list(size=11)))
}

# function to plot cumulative cases by region
country_region_cases_cumulative = function(covid19_cases, start_point=c("Date", "Day of 100th confirmed case", "Day of 10th death")) {
                            if (start_point=="Date") {
                              g = ggplot(covid19_cases, 
                                         aes(x = date, 
                                             y = outcome, 
                                             colour = region, 
                                             group = 1,
                                             text = paste0(format(date, "%d %B %Y"), "\n", region, ": ",outcome))) +
                                  xlim(c(cv_min_date,current_date+1)) + 
                                  xlab("Date")
                            }
  
                            if (start_point=="Day of 100th confirmed case") {
                              covid19_cases = subset(covid19_cases, days_since_case100>0)
                              
                              g = ggplot(covid19_cases, 
                                         aes(x = days_since_case100, 
                                             y = outcome, 
                                             colour = region, 
                                             group = 1,
                                             text = paste0("Day ", days_since_case100,"\n", region, ": ",outcome))) +
                                  xlab("Days since 100th confirmed case")
                            }
  
                            if (start_point=="Day of 10th death") {
                              covid19_cases = subset(covid19_cases, days_since_death10>0)
                              g = ggplot(covid19_cases, 
                                         aes(x = days_since_death10, 
                                             y = outcome, 
                                             colour = region, 
                                             group = 1,
                                             text = paste0("Day ", days_since_death10,"\n", region, ": ",outcome))) +
                                  xlab("Days since 10th death")
                            }
  
  g1 = g + 
        geom_line(alpha=0.8) + 
        geom_point(size = 1, alpha = 0.8) +
        ylab("cumulative") + 
        theme_bw() + 
        scale_colour_manual(values=country_cols) +
        theme(legend.title = element_blank(), legend.position = "", plot.title = element_text(size=10))
  
  ggplotly(g1, tooltip = c("text")) %>% 
    layout(legend = list(font = list(size=11)))
}

# function to plot cumulative cases by region on log10 scale
country_region_cases_cumulative_log = function(covid19_cases, start_point=c("Date", "Day of 100th confirmed case", "Day of 10th death"))  {
                                if (start_point=="Date") {
                                  g = ggplot(covid19_cases, 
                                             aes(x = date, 
                                                 y = outcome, 
                                                 colour = region, 
                                                 group = 1,
                                                 text = paste0(format(date, "%d %B %Y"), "\n", region, ": ",outcome))) +
                                    xlim(c(cv_min_date,current_date+1)) +
                                    xlab("Date")
                                }
                                
                                if (start_point=="Day of 100th confirmed case") {
                                  covid19_cases = subset(covid19_cases, days_since_case100>0)
                                  g = ggplot(covid19_cases, 
                                             aes(x = days_since_case100, 
                                                 y = outcome, 
                                                 colour = region, 
                                                 group = 1,
                                                 text = paste0("Day ",days_since_case100, "\n", region, ": ",outcome))) +
                                    xlab("Days since 100th confirmed case")
                                }
                                
                                if (start_point=="Day of 10th death") {
                                  covid19_cases = subset(covid19_cases, days_since_death10>0)

                                  g = ggplot(covid19_cases, 
                                             aes(x = days_since_death10, 
                                                 y = outcome, 
                                                 colour = region, 
                                                 group = 1,
                                                 text = paste0("Day ",days_since_death10, "\n", region, ": ",outcome))) +
                                      xlab("Days since 10th death")
                                }
  
  g1 = g + 
        geom_line(alpha=0.8) + 
        geom_point(size = 1, alpha = 0.8) +
        ylab("cumulative (log10)") + theme_bw() +
        scale_y_continuous(trans="log10") +
        scale_colour_manual(values=country_cols) +
        theme(legend.title = element_blank(), legend.position = "", plot.title = element_text(size=10))
  
  ggplotly(g1, tooltip = c("text")) %>% 
    layout(legend = list(font = list(size=11)))
}

# function to plot cumulative COVID cases by date
cumulative_plot = function(covid19_aggregated, plot_date) {
                    plot_df = subset(covid19_aggregated, date<=plot_date)
                    
                    g1 = ggplot(plot_df, aes(x = date, y = cases, color = region)) + 
                          geom_line() + 
                          geom_point(size = 1, alpha = 0.8) +
                          ylab("cumulative cases") + theme_bw() + 
                          scale_colour_manual(values=c(cv19_color)) +
                          scale_y_continuous(labels = function(l) {trans = l / 1000; paste0(trans, "K")}) +
                          theme(legend.title = element_blank(), 
                                legend.position = "", 
                                plot.title = element_text(size=10), 
                                plot.margin = margin(5, 12, 5, 5))
  g1
}

# function to plot new COVID cases by date
new_cases_plot = function(covid19_aggregated, plot_date) {
                  plot_df_new = subset(covid19_aggregated, date<=plot_date)
                  
                  g1 = ggplot(plot_df_new, aes(x = date, y = new, fill = region)) + 
                              geom_bar(position="stack", stat="identity") + 
                              ylab("new cases") + 
                              theme_bw() + 
                              scale_fill_manual(values=c(cv19_color)) +
                              scale_y_continuous(labels = function(l) {trans = l / 1000; paste0(trans, "K")}) +
                              theme(legend.title = element_blank(), 
                                    legend.position = "", 
                                    plot.title = element_text(size=10), 
                                    plot.margin = margin(5, 12, 5, 5))
                  g1
}

usastates_plot = function(covid19_us_states_aggregated, usastates_plot_date, us_state_outcome_select = 'Cases') {
  cv_us_states_plot_df_new = subset(covid19_us_states, date<=usastates_plot_date)
  
  if(us_state_outcome_select == "Deaths") {
    covid19_us_states_aggregated = aggregate(cv_us_states_plot_df_new$deaths, by=list(Category=cv_us_states_plot_df_new$state), FUN=sum)
  } else {
    covid19_us_states_aggregated = aggregate(cv_us_states_plot_df_new$cases, by=list(Category=cv_us_states_plot_df_new$state), FUN=sum)
  }
  
  names(covid19_us_states_aggregated) = c("region", "value")
  covid19_us_states_aggregated <- covid19_us_states_aggregated %>% 
                              mutate(region = tolower(region), value = value) %>% 
                              arrange(region)
  
  
  g <- state_choropleth(covid19_us_states_aggregated, title=paste0("Reported date : ", usastates_plot_date), legend=us_state_outcome_select, num_colors = 1)
  g
}

usastates_plot2 = function(covid19_us_states, usastates_plot_date2, us_state_outcome_select2) {
    covid19_us_states$date = as.Date(covid19_us_states$date,"%Y-%m-%d")
    cv_us_states_plot_df_new = subset(covid19_us_states, date<=usastates_plot_date2)

    if(us_state_outcome_select2 == "Deaths") {
      covid19_us_states_aggregated = aggregate(cv_us_states_plot_df_new$deaths, by=list(Category=cv_us_states_plot_df_new$state), FUN=sum)
    } else {
      covid19_us_states_aggregated = aggregate(cv_us_states_plot_df_new$cases, by=list(Category=cv_us_states_plot_df_new$state), FUN=sum)
    }
    names(covid19_us_states_aggregated) = c("state", "cases")

    states$cases <- 0
    for (i in 1:length(states$name)) { 
      states$cases[i] = as.integer(covid19_us_states_aggregated %>% filter(states$name[i] == covid19_us_states_aggregated$state) %>% select(cases))
    }
    states$cases[is.na(states$cases)] <- 0
    
    bins <- c(0, 10, 20, 50, 100, 200, 500, 1000, 5000, 10000, 20000, 30000, Inf)
    pal <- colorBin("Blues", domain = states$cases, bins = bins)

    labels <- sprintf("<strong>%s</strong><br/>%g people %s",states$name, states$cases, us_state_outcome_select2) %>% lapply(htmltools::HTML)

    g1 <- leaflet(states) %>%
      setView(-96, 37.8, 4) %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      addPolygons(
        fillColor = ~pal(cases),
        weight = 2,
        opacity = 1,
        color = "white",
        dashArray = "3",
        fillOpacity = 0.7,
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE),
        label = labels,
        labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"),textsize = "15px",direction = "auto")) %>%
      addLegend(pal = pal, values = ~cases, opacity = 0.7, title = NULL,position = "bottomright")
    g1
}

# function to plot cumulative sars cases by date
sars_cumulative_plot = function(sars_aggregated, sars_date) {
                        plot_df = subset(sars_aggregated, date<=as.Date(sars_date, format="%Y-%m-%d"))
  
                        ggplot(plot_df, aes(x = date, y = cases)) + 
                          geom_line(colour = sars_color) + 
                          geom_point(size = 1, alpha = 0.8, colour = sars_color) +
                          ylab("cumulative cases") + 
                          theme_bw() + 
                          scale_colour_manual(values=c(sars_color)) + 
                          scale_x_date(date_labels = "%b", limits=c(sars_min_date,sars_max_date)) +
                          scale_y_continuous(limits=c(0,10000), labels = function(l) {trans = l / 1000; paste0(trans, "K")}) +
                          theme(legend.title = element_blank(), 
                                legend.position = "", 
                                plot.title = element_text(size=10), 
                                plot.margin = margin(5, 5, 5, 5))
  }

# function to plot new cases by date
sars_new_cases_plot = function(sars_aggregated, plot_date) {
                        plot_df_new = subset(sars_aggregated, date<=plot_date)
                        
                        ggplot(plot_df_new, aes(x = date, y = new)) + 
                                geom_bar(position="stack", stat="identity", fill = sars_color) + 
                                ylab("new cases") + 
                                theme_bw() + 
                                ylim(0,2000) + 
                                scale_fill_manual(values=c(sars_color)) +
                                xlim(c(sars_min_date,sars_max_date)) + 
                                scale_x_date(date_labels = "%b", 
                                             limits=c(sars_min_date,sars_max_date)) +
                                              theme(legend.title = element_blank(), 
                                                    legend.position = "", 
                                                    plot.title = element_text(size=10), 
                                                    plot.margin = margin(5, 5, 5, 5))
}



# function to render plotly of epidemic comparison depending on selected outcome
comparison_plot = function(epi_comp, comparison) {
  epi_comp$outcome = epi_comp[,comparison] 
  epi_comp = epi_comp[order(epi_comp$outcome),]
  epi_comp$outbreak = factor(epi_comp$outbreak, levels=epi_comp$outbreak)
  
  p1 <- ggplot(epi_comp, 
               aes(x = outbreak, 
                   y = outcome, 
                   fill=outbreak, 
                   text = paste0(outbreak, ": ",outcome))) + 
               geom_bar(alpha = 0.8, stat="identity") +
               ylab("N") + 
               xlab("") + 
               theme_bw() + 
               scale_fill_manual(values=c("2019-COVID"=cv19_color, 
                                          "2003-SARS"=sars_color, 
                                          "2014-Ebola"=ebola_color,
                                          "2009-H1N1 (swine flu)"=h1n1_color)) +
               theme(legend.position = "")
  
  if(comparison == "cfr") { 
    p1 = p1 + ylab("%") 
  }
  
  if(comparison == "deaths") { 
    p1 = p1 + 
          scale_y_continuous(labels = function(l) {
            trans = l / 1000; paste0(trans, "K")
          }) 
  }

  if(comparison == "cases") { 
    p1 = p1 + 
          scale_y_continuous(trans='log10', 
                             limits = c(1,1e8), 
                             breaks=c(1,1000,1e6,1e9), 
                             labels = function(l) {
                               trans = l / 1000; paste0(trans, "K")
                             }) 
  }
  
  ggplotly(p1 + coord_flip(), tooltip = c("text")) %>% 
    layout(showlegend = FALSE)
}


```

```{r data-processing-1, echo=FALSE}
# extract time stamp from covid19_cases
update = tail(covid19_cases$last_update,1) 

# check consistency of country names across datasets
if (all(unique(covid19_cases$country) %in% unique(countries$country))==FALSE) { 
  print("Error: inconsistent country names")
}

# extract dates from cv data
if (any(grepl("/", covid19_cases$date))) { 
  covid19_cases$date = format(as.Date(covid19_cases$date, format="%d/%m/%Y"),"%Y-%m-%d") 
} else { 
  covid19_cases$date = as.Date(covid19_cases$date, format="%Y-%m-%d") 
}
covid19_cases$date = as.Date(covid19_cases$date)
cv_min_date = as.Date(min(covid19_cases$date),"%Y-%m-%d")
current_date = as.Date(max(covid19_cases$date),"%Y-%m-%d")
cv_max_date_clean = format(as.POSIXct(current_date),"%d %B %Y")

# merge cv data with country data and extract key summary variables
covid19_cases = merge(covid19_cases, countries, by = "country")
covid19_cases = covid19_cases[order(covid19_cases$date),]

#covid19_cases$per100k = as.numeric(format(round(covid19_cases$cases/(covid19_cases$population/100000),1),nsmall=1))
covid19_cases$per100k = format(round(covid19_cases$cases/(covid19_cases$population/100000),1),nsmall=1)
covid19_cases$per100k[is.na(covid19_cases$per100k)] <- 0
covid19_cases$per100k <- as.numeric(covid19_cases$per100k)

#covid19_cases$newper100k = as.numeric(format(round(covid19_cases$new_cases/(covid19_cases$population/100000),1),nsmall=1))
covid19_cases$newper100k = format(round(covid19_cases$new_cases/(covid19_cases$population/100000),1),nsmall=1)
covid19_cases$newper100k[is.na(covid19_cases$newper100k)] <- 0
covid19_cases$newper100k <- as.numeric(covid19_cases$newper100k)


#covid19_cases$activeper100k = as.numeric(format(round(covid19_cases$active_cases/(covid19_cases$population/100000),1),nsmall=1))
covid19_cases$activeper100k = format(round(covid19_cases$active_cases/(covid19_cases$population/100000),1),nsmall=1)
covid19_cases$activeper100k[is.na(covid19_cases$activeper100k)] <- 0
covid19_cases$activeper100k <- as.numeric(covid19_cases$activeper100k)

covid19_cases$million_pop = as.numeric(covid19_cases$population>1e6)

# add variable for days since 100th case and 10th death
covid19_cases$days_since_case100 = covid19_cases$days_since_death10 = 0
for (i in 1:length(unique(covid19_cases$country))) {
  country_name = as.character(unique(covid19_cases$country))[i]
  country_db = subset(covid19_cases, country==country_name)
  country_db$days_since_case100[country_db$cases>=100] = 1:sum(country_db$cases>=100)
  country_db$days_since_death10[country_db$deaths>=10] = 1:sum(country_db$deaths>=10)
  covid19_cases$days_since_case100[covid19_cases$country==country_name] = country_db$days_since_case100
  covid19_cases$days_since_death10[covid19_cases$country==country_name] = country_db$days_since_death10
}

# creat variable for today's data
covid19_today = subset(covid19_cases, date==current_date) 
current_case_count = sum(covid19_today$cases)
current_case_count_China = sum(covid19_today$cases[covid19_today$country=="Mainland China"])
current_case_count_other = sum(covid19_today$cases[covid19_today$country!="Mainland China"])
current_death_count = sum(covid19_today$deaths)

# create subset for countries with at least 100 cases
cv_today_100 = subset(covid19_today, cases>=100)

# write current day's data
write.csv(covid19_today %>% select(c(country, date, update, cases, new_cases, deaths, new_deaths,
                                recovered, new_recovered, active_cases, 
                                per100k, newper100k, activeper100k,
                                days_since_case100, days_since_death10)), "source/coronavirus_today.csv")

# aggregate at continent level
cv_cases_continent = subset(covid19_cases, !is.na(continent_level)) %>% 
                      select(c(cases, new_cases, deaths, new_deaths, date, continent_level)) %>% 
                      group_by(continent_level, date) %>% 
                      summarise_each(funs(sum)) %>% 
                      data.frame()

# add variable for days since 100th case and 10th death
cv_cases_continent$days_since_case100 = cv_cases_continent$days_since_death10 = 0
cv_cases_continent$continent = cv_cases_continent$continent_level
for (i in 1:length(unique(cv_cases_continent$continent))) {
  continent_name = as.character(unique(cv_cases_continent$continent))[i]
  continent_db = subset(cv_cases_continent, continent==continent_name)
  continent_db$days_since_case100[continent_db$cases>=100] = 1:sum(continent_db$cases>=100)
  continent_db$days_since_death10[continent_db$deaths>=10] = 1:sum(continent_db$deaths>=10)
  cv_cases_continent$days_since_case100[cv_cases_continent$continent==continent_name] = continent_db$days_since_case100
  cv_cases_continent$days_since_death10[cv_cases_continent$continent==continent_name] = continent_db$days_since_death10
}
write.csv(cv_cases_continent, "source/coronavirus_continent.csv")

# aggregate at global level
cv_cases_global = covid19_cases %>% 
                    select(c(cases, new_cases, deaths, new_deaths, date, global_level)) %>% 
                    group_by(global_level, date) %>% 
                    summarise_each(funs(sum)) %>% 
                    data.frame()
cv_cases_global$days_since_case100 = cv_cases_global$days_since_death10 = 1:nrow(cv_cases_global)
write.csv(cv_cases_global, "source/coronavirus_global.csv")


alpha3 = ''
# select large countries for mapping polygons
cv_large_countries = covid19_today %>% 
                      filter(alpha3 %in% worldcountry$id)

if (all(cv_large_countries$alpha3 %in% worldcountry$id)==FALSE) { 
  print("Error: inconsistent country names")
}
cv_large_countries = cv_large_countries[order(cv_large_countries$alpha3),]

cv_usa <- cv_large_countries %>% 
                      filter('USA' == cv_large_countries$alpha3)

# create plotting parameters for map
bins = c(0,1,5,10,50,100,500,1000,10000,Inf)
cv_pal <- colorBin("Oranges", domain = cv_large_countries$per100k, bins = bins)
plot_map <- worldcountry[worldcountry$id %in% cv_large_countries$alpha3, ]

# creat cv base map 
basemap = leaflet(plot_map) %>% 
          addTiles() %>% 
          addLayersControl(
                            position = "bottomright",
                            overlayGroups = c("2019-COVID (active)", 
                                              "2019-COVID (new)", 
                                              "2019-COVID (cumulative)", 
                                              "2003-SARS", 
                                              "2009-H1N1 (swine flu)", 
                                              "2014-Ebola"),
                            options = layersControlOptions(collapsed = FALSE)) %>% 
          #hideGroup(c("2019-COVID (new)", "2019-COVID (cumulative)", "2003-SARS", "2009-H1N1 (swine flu)", "2014-Ebola"))  %>%
          hideGroup(c("2003-SARS", "2009-H1N1 (swine flu)", "2014-Ebola"))  %>%
          addProviderTiles(providers$CartoDB.Positron) %>%
          fitBounds(~-100,-50,~80,80) %>%
          addLegend("bottomright", 
                    pal = cv_pal, 
                    values = ~cv_large_countries$per100k,
                    title = "<small>Active cases per 100,000</small>") #%>%
#fitBounds(0,-25,90,65) # alternative coordinates for closer zoom

# sum cv case counts by date
covid19_aggregated = aggregate(covid19_cases$cases, by=list(Category=covid19_cases$date), FUN=sum)
names(covid19_aggregated) = c("date", "cases")

# add variable for new cases in last 24 hours
for (i in 1:nrow(covid19_aggregated)) { 
  if (i==1) { 
    covid19_aggregated$new[i] = 0 
  }
  if (i>1) { 
    covid19_aggregated$new[i] = covid19_aggregated$cases[i] - covid19_aggregated$cases[i-1] 
  }
}

# add plotting region
covid19_aggregated$region = "Global"
covid19_aggregated$date = as.Date(covid19_aggregated$date,"%Y-%m-%d")

# assign colours to countries to ensure consistency between plots 
cls = rep(c(brewer.pal(8,"Dark2"), 
            brewer.pal(10, "Paired"), 
            brewer.pal(12, "Set3"), 
            brewer.pal(8,"Set2"), 
            brewer.pal(9, "Set1"), 
            brewer.pal(8, "Accent"),  
            brewer.pal(9, "Pastel1"),  
            brewer.pal(8, "Pastel2")),3)

cls_names = c(as.character(unique(covid19_cases$country)), as.character(unique(cv_cases_continent$continent)),"Global")
country_cols = cls[1:length(cls_names)]
names(country_cols) = cls_names

covid19_us_states$date = as.Date(covid19_us_states$date)
cv_us_min_date = as.Date(min(covid19_us_states$date),"%Y-%m-%d")
us_current_date= as.Date(max(covid19_us_states$date), "%Y-%m-%d")

cv_rawtable <- covid19_cases %>% select(c(country, date, cases, new_cases, deaths, new_deaths,
                                     recovered, new_recovered, active_cases, per100k, newper100k, activeper100k)) 

covid19_us_states$date = as.Date(covid19_us_states$date,"%Y-%m-%d")
```


```{r data-processing-2, echo=FALSE}
### DATA PROCESSING: SARS ###

# extract dates from sars data
sars_cases$date = as.Date(sars_cases$date, format="%d/%m/%Y")
sars_min_date = min(sars_cases$date)
sars_max_date = max(sars_cases$date)
sars_max_date_clean = format(as.POSIXct(sars_max_date),"%d %B %Y")

# merge sars data with country data and extract key summary variables

sars_cases = merge(sars_cases, countries, by = "country")
sars_cases = sars_cases[order(sars_cases$date),]
sars_cases$per100k = as.numeric(format(round(sars_cases$cases/(sars_cases$population/100000),1),nsmall=1))
sars_final = subset(sars_cases, date==sars_max_date) 
sars_final_case_count = sum(sars_final$cases)

# select polygons for sars base map
sars_large_countries = sars_final %>% filter(country %in% country_geoms$countries_present)
sars_large_countries = sars_large_countries[order(sars_large_countries$alpha3),]
sars_plot_map <- worldcountry[worldcountry$id %in% sars_large_countries$alpha3, ]

# create plotting parameters for sars map
sars_pal <- colorBin("Blues", domain = sars_large_countries$per100k, bins = bins)

# creat sars interactive map (needs to include polygons and circles as slider input not recognised upon initial loading)
sars_basemap = leaflet(sars_plot_map) %>% 
                addTiles() %>% 
                addLayersControl(
                  position = "bottomright",
                  overlayGroups = c("2003-SARS (cumulative)", 
                                    "2019-COVID", 
                                    "2009-H1N1 (swine flu)", 
                                    "2014-Ebola"),
                  options = layersControlOptions(collapsed = FALSE)) %>% 
  
                  hideGroup(c("2019-COVID", "2009-H1N1 (swine flu)", "2014-Ebola"))  %>%
                  addProviderTiles(providers$CartoDB.Positron) %>%
                  fitBounds(~-100,-50,~80,80) %>%
  
  addPolygons(stroke = FALSE, 
              smoothFactor = 0.2, 
              fillOpacity = 0.1, 
              fillColor = ~sars_pal(sars_large_countries$per100k), 
              group = "2003-SARS (cumulative)",
              label = sprintf("<strong>%s</strong><br/>SARS cases: %g<br/>Deaths: %d<br/>Cases per 100,000: %g", 
                              sars_large_countries$country, 
                              sars_large_countries$cases, 
                              sars_large_countries$deaths, 
                              sars_large_countries$per100k) %>% 
              lapply(htmltools::HTML),
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px", "color" = sars_color),
                textsize = "15px", direction = "auto")) %>%
  
  
  addCircleMarkers(data = sars_final, 
                   lat = ~ latitude, 
                   lng = ~ longitude, 
                   weight = 1, 
                   radius = ~(cases)^(1/4), 
                   fillOpacity = 0.2, 
                   color = sars_color, 
                   group = "2003-SARS (cumulative)",
                   label = sprintf("<strong>%s</strong><br/>SARS cases: %g<br/>Deaths: %d<br/>Cases per 100,000: %g", 
                                   sars_final$country, 
                                   sars_final$cases, 
                                   sars_final$deaths, 
                                   sars_final$per100k) %>% 
                   lapply(htmltools::HTML),
                   labelOptions = labelOptions(
                                                style = list("font-weight" = "normal", padding = "3px 8px", "color" = sars_color),
                                                textsize = "15px", 
                                                direction = "auto")) %>%
  
  addCircleMarkers(data = covid19_today, 
                   lat = ~ latitude, 
                   lng = ~ longitude, 
                   weight = 1, 
                   radius = ~(cases)^(1/5),
                   fillOpacity = 0.2, 
                   color = cv19_color, 
                   group = "2019-COVID",
                   label = sprintf("<strong>%s (cumulative)</strong><br/>Confirmed cases: %g<br/>Deaths: %d<br/>Recovered: %d<br/>Cases per 100,000: %g", covid19_today$country, covid19_today$cases, covid19_today$deaths, covid19_today$recovered, covid19_today$per100k) %>% 
                   lapply(htmltools::HTML),
                   labelOptions = labelOptions(
                                                style = list("font-weight" = "normal", padding = "3px 8px", "color" = cv19_color),
                                                textsize = "15px", 
                                                direction = "auto")) 
   





  
# sum sars case counts by date
sars_aggregated = aggregate(sars_cases$cases, by=list(Category=sars_cases$date), FUN=sum)
names(sars_aggregated) = c("date", "cases")

# add variable for new sars cases in last 7 days
for (i in 1:nrow(sars_aggregated)) { 
  if (i==1) { 
    sars_aggregated$new[i] = NA 
  }
  
  if (i>1) { 
    sars_aggregated$new[i] = sars_aggregated$cases[i] - sars_aggregated$cases[i-1] 
  }
}
sars_aggregated$new[sars_aggregated$new<0] = 0

### OUTBREAK COMPARISON DATA ###

# load epidemic comparison data
epi_comp = as.data.frame(data.table::fread("source/epi_comp.csv"))
epi_comp$outbreak = factor(epi_comp$outbreak, levels = epi_comp$outbreak)
epi_comp$cases[1] = current_case_count
epi_comp$deaths[1] = current_death_count
epi_comp$countries[1] = nrow(subset(covid19_today, country!="Diamond Princess Cruise Ship"))
epi_comp$cfr[1] = round(epi_comp$deaths[1]/epi_comp$cases[1]*100,1)
epi_comp$cfr = round(epi_comp$cfr,2)

```

```{r shiny-ui}
ui <- bootstrapPage(
  navbarPage(theme = shinytheme("slate"), collapsible = TRUE,
             "Dashboard", id="nav",
             tabPanel("World Covid-19 mapper",
                      div(class="outer",
                          tags$head(includeCSS("styles.css")),
                          leafletOutput("mymap", width="100%", height="100%"),
                          
                          absolutePanel(id = "controls", class = "panel panel-default",
                                        top = 70, left = 50, width = 250, fixed=TRUE,draggable = TRUE, height = "auto",
                                        tags$span(h2(textOutput("clean_date_reactive"), align = "center"),style="color:#D1E169"),
                                        tags$span(h2("Global", align = "center"),style="color:#ffffff"),
                                        
                                        tags$span(h3(textOutput("reactive_case_count"), align = "center"), style="color:#FFA500"),
                                        tags$span(h4(textOutput("reactive_death_count"), align = "center"),style="color:#FF0000"),
                                        tags$span(h4(textOutput("reactive_recovered_count"), align = "center"), style="color:#006d2c"),
                                        tags$span(h4(textOutput("reactive_active_count"), align = "center"), style="color:#cc4c02"),
                                        
                                        tags$span(h2("USA", align = "center"),style="color:#ffffff"),
                                        tags$span(h3(textOutput("reactive_us_case_count"), align = "center"), style="color:#FFA500"),
                                        tags$span(h4(textOutput("reactive_us_death_count"), align = "center"), style="color:#FF0000"),
                                        tags$span(h4(textOutput("reactive_us_recovered_count"), align = "center"), style="color:#006d2c"),
                                        
                                        br(),
                                        h6(textOutput("reactive_country_count"), align = "center"),
                                        plotOutput("epi_curve", height="130px", width="100%"),
                                        plotOutput("cumulative_plot", height="130px", width="100%"),
                                        
                                       
                                        sliderInput("plot_date",
                                                    label = h5("Select mapping date"),
                                                    min = as.Date(cv_min_date,"%Y-%m-%d"),
                                                    max = as.Date(current_date,"%Y-%m-%d"),
                                                    value = as.Date(current_date),
                                                    timeFormat = "%d %b", 
                                                    animate=animationOptions(interval = 2000, loop = FALSE))
                                        
                                        
                          )
                          
                          
                      )
             ),
             tabPanel("Country/Region plots",
                      
                      sidebarLayout(
                        sidebarPanel(
                          "Select outcome, regions, and plotting start date from drop-down menues to update plots.",
                          pickerInput("level_select", "Level:",   
                                      choices = c("Global", "Continent", "Country"), 
                                      selected = c("Country"),
                                      multiple = FALSE),
                          
                          pickerInput("region_select", "Country/Region:",   
                                      choices = as.character(cv_today_100[order(-cv_today_100$cases),]$country), 
                                      options = list(`actions-box` = TRUE, `none-selected-text` = "Please make a selection!"),
                                      selected = cv_today_100$country,
                                      multiple = TRUE), 
                          
                          pickerInput("outcome_select", "Outcome:",   
                                      choices = c("Cases", "Deaths", "Recovered"), 
                                      selected = c("Cases"),
                                      multiple = FALSE),
                          
                          pickerInput("start_date", "Plotting start date:",   
                                      choices = c("Date", "Day of 100th confirmed case", "Day of 10th death"), 
                                      options = list(`actions-box` = TRUE),
                                      selected = "Date",
                                      multiple = FALSE)
                        ),
                        
                        mainPanel(
                          tabsetPanel(
                            tabPanel("New", plotlyOutput("country_plot")),
                            tabPanel("Cumulative", plotlyOutput("country_plot_cumulative")),
                            tabPanel("Cumulative (log10)", plotlyOutput("country_plot_cumulative_log"))
                          )
                        )
                      )
             ),

             tabPanel("USA mapper",
                      sidebarLayout(
                        sidebarPanel(
                          pickerInput("us_state_outcome_select", "Outcome:",   
                                      choices = c("Cases", "Deaths"), 
                                      selected = c("Cases"),
                                      multiple = FALSE),
                          
                          sliderInput("us_plot_start_date",
                                                    label = h5("Select date"),
                                                    min = as.Date(cv_us_min_date,"%Y-%m-%d"),
                                                    max = as.Date(us_current_date,"%Y-%m-%d"),
                                                    value = as.Date(us_current_date),
                                                    timeFormat = "%d %b", 
                                                    animate=animationOptions(interval = 2000, loop = FALSE))
                        ),
                        mainPanel(plotOutput(outputId = "usastates_plot"), width = 6)
                      )
             ),
             tabPanel("USA mapper (New)",
                      sidebarLayout(
                        sidebarPanel(
                          pickerInput("us_state_outcome_select2", "Outcome:",   
                                      choices = c("Cases", "Deaths"), 
                                      selected = c("Cases"),
                                      multiple = FALSE),
                          
                          sliderInput("us_plot_start_date2",
                                                    label = h5("Select date"),
                                                    min = as.Date(cv_us_min_date,"%Y-%m-%d"),
                                                    max = as.Date(us_current_date,"%Y-%m-%d"),
                                                    value = as.Date(us_current_date),
                                                    timeFormat = "%d %b", 
                                                    animate=animationOptions(interval = 2000, loop = FALSE))
                        ),
                        mainPanel(leafletOutput("usastates_plot2"))
                      )
             ),
             tabPanel("SARS plot",
                      div(class="outer",
                          tags$head(includeCSS("styles.css")),
                          leafletOutput("sars_map", width="100%", height="100%"),
                          
                          absolutePanel(id = "controls", class = "panel panel-default",
                                        top = 80, left = 20, width = 250, fixed=TRUE,
                                        draggable = TRUE, height = "auto",
                                        
                                        tags$span(h3(textOutput("sars_reactive_case_count"), align = "center"), style="color:#FFA500"),
                                        tags$span(h4(textOutput("sars_reactive_death_count"), align = "center"),style="color:#FF0000"),
                                        tags$span(h6(textOutput("sars_clean_date_reactive"), align = "center"),style="color:#ffffff"),
                                        tags$span(h6(textOutput("sars_reactive_country_count"), align = "center"),style="color:#ffffff"),
                                        plotOutput("sars_epi_curve", height="130px", width="100%"),
                                        plotOutput("sars_cumulative_plot", height="130px", width="100%"),
                                        tags$span(("Circles show confirmed cases for COVID, SARS, and Ebola, and estimated deaths for H1N1."),
                                             align = "left", style = "font-size:80%"),
                                        
                                        sliderTextInput("sars_plot_date",
                                                        label = h5("Select date"),
                                                        choices = format(unique(sars_cases$date), "%d %b %y"),
                                                        selected = format(sars_max_date, "%d %b %y"),
                                                        grid = TRUE,
                                                        animate=animationOptions(interval = 2000, loop = FALSE))
                          )
                      )
             ),
             tabPanel("Epidemic Comparisons",
                      
                      sidebarLayout(
                        sidebarPanel(
                          radioButtons("comparison_metric", h3("Select comparison:"),
                                       c("Cases" = "cases",
                                         "Deaths" = "deaths",
                                         "Countries/regions affected" = "countries",
                                         "Case fatality rate" = "cfr")),
                          textOutput("epi_notes_1"),
                          textOutput("epi_notes_2"),
                          textOutput("epi_notes_3")
                        ),
                        
                        mainPanel(plotlyOutput("comparison_plot"))
                      )
             ),
             
             tabPanel("Tabular Data",
                      numericInput("maxrows", "Rows to show", 20),
                      # verbatimTextOutput("rawtable")
                      tableOutput('rawtable')
             )
             
  )          
)

```

```{r shiny-server, echo=TRUE}
### SHINY SERVER ###

server = function(input, output, session) {

  # covid tab 
  output$clean_date_reactive <- renderText({
    format(as.POSIXct(input$plot_date),"%d %B %Y")
  })
  
  reactive_db = reactive({
    covid19_cases %>% filter(date == input$plot_date)
    # reactive = covid19_cases %>% filter(date == "2020-04-07")
  })
  
  reactive_db_last24h = reactive({
    covid19_cases %>% filter(date == input$plot_date & new_cases>0)
  })
  
  reactive_db_large = reactive({
    large_countries = reactive_db() %>% filter(alpha3 %in% worldcountry$id)
   #large_countries = reactive %>% filter(alpha3 %in% worldcountry$id)
    worldcountry_subset = worldcountry[worldcountry$id %in% large_countries$alpha3, ]
    large_countries = large_countries[match(worldcountry_subset$id, large_countries$alpha3),]
    large_countries
  })
  
  reactive_db_large_last24h = reactive({
    large_countries = reactive_db_last24h() %>% filter(alpha3 %in% worldcountry$id)
    large_countries = large_countries[order(large_countries$alpha3),]
    large_countries
  })
  
  reactive_polygons = reactive({
    worldcountry[worldcountry$id %in% reactive_db_large()$alpha3, ]
  })
  
  reactive_polygons_last24h = reactive({
    worldcountry[worldcountry$id %in% reactive_db_large_last24h()$alpha3, ]
  })
  
  output$reactive_case_count <- renderText({
    paste0(prettyNum(sum(reactive_db()$cases), big.mark=","), " cases")
  })
  
  output$reactive_death_count <- renderText({
    paste0(prettyNum(sum(reactive_db()$death), big.mark=","), " deaths")
  })
  
  output$reactive_recovered_count <- renderText({
    paste0(prettyNum(sum(reactive_db()$recovered), big.mark=","), " recovered")
  })
  
  output$reactive_active_count <- renderText({
    paste0(prettyNum(sum(reactive_db()$active_cases), big.mark=","), " active cases")
  })
  
  
  ### Viren ###
  output$reactive_us_case_count <- renderText({
    paste0(prettyNum(cv_usa['cases'], big.mark=","), " cases")
  })
  
  output$reactive_us_death_count <- renderText({
    paste0(prettyNum(cv_usa['deaths'], big.mark=","), " deaths")
  })
  
  output$reactive_us_recovered_count <- renderText({
    paste0(prettyNum(cv_usa['recovered'], big.mark=","), " recovered")
  })
  ### Viren ###

  output$reactive_case_count_China <- renderText({
    paste0("Mainland China: ", prettyNum(sum(subset(reactive_db(), country=="Mainland China")$cases), big.mark=",")," (",
           prettyNum((covid19_aggregated %>% filter(date == input$plot_date & region=="Mainland China"))$new, big.mark=",")," new)")
  })
  
  output$reactive_case_count_row <- renderText({
    paste0("Other: ", prettyNum(sum(subset(reactive_db(), country!="Mainland China")$cases), big.mark=",")," (",
           prettyNum((covid19_aggregated %>% filter(date == input$plot_date & region=="Other"))$new, big.mark=",")," new)")
  })
  
  output$reactive_country_count <- renderText({
    paste0(nrow(subset(reactive_db(), country!="Diamond Princess Cruise Ship")), " countries/regions affected")
  })
  
  output$reactive_new_cases_24h <- renderText({
    paste0((covid19_aggregated %>% filter(date == input$plot_date & region=="Global"))$new, " new in last 24h")
  })
  
  output$mymap <- renderLeaflet({ 
    basemap
  })
  
  
  observeEvent(input$plot_date, {
    leafletProxy("mymap") %>% 
    clearMarkers() %>%
    clearShapes() %>%
    addPolygons(data = reactive_polygons(), 
                stroke = FALSE, 
                smoothFactor = 0.2, 
                fillOpacity = 1, 
                fillColor = ~cv_pal(reactive_db_large()$activeper100k)) %>% 
      
    addCircleMarkers(data = reactive_db_last24h(), 
                     lat = ~ latitude, 
                     lng = ~ longitude, 
                     weight = 1, 
                     radius = ~(new_cases)^(1/5), 
                     fillOpacity = 0.1, 
                     color = cv19_color, 
                     group = "2019-COVID (new)",
                     label = sprintf("<strong>%s (past 24h)</strong><br/>Confirmed cases: %g<br/>Deaths: %d<br/>Recovered: %d<br/>Cases per 100,000: %g", reactive_db_last24h()$country, reactive_db_last24h()$new_cases, reactive_db_last24h()$new_deaths, reactive_db_last24h()$new_recovered, reactive_db_last24h()$newper100k) %>% 
                     lapply(htmltools::HTML),
                     labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px", "color" = cv19_color),
                                                  textsize = "15px", 
                                                  direction = "auto")) %>%
      
      addCircleMarkers(data = reactive_db(), 
                       lat = ~ latitude, 
                       lng = ~ longitude, 
                       weight = 1, 
                       radius = ~(cases)^(1/5), 
                       fillOpacity = 0.1, 
                       color = cv19_color, 
                       group = "2019-COVID (cumulative)",
                       label = sprintf("<strong>%s (cumulative)</strong><br/>Confirmed cases: %g<br/>Deaths: %d<br/>Recovered: %d<br/>Cases per 100,000: %g", reactive_db()$country, reactive_db()$cases, reactive_db()$deaths,reactive_db()$recovered, reactive_db()$per100k) %>%   lapply(htmltools::HTML),
                       labelOptions = labelOptions(
                                            style = list("font-weight" = "normal", padding = "3px 8px", "color" = cv19_color),
                                            textsize = "15px", direction = "auto")) %>%

      addCircleMarkers(data = reactive_db(), 
                       lat = ~ latitude, 
                       lng = ~ longitude, 
                       weight = 1, 
                       radius = ~(active_cases)^(1/5), 
                       fillOpacity = 0.1, 
                       color = cv19_color, 
                       group = "2019-COVID (active)",
                       label = sprintf("<strong>%s (active)</strong><br/>Confirmed cases: %g<br/>Cases per 100,000: %g<br/><i><small>Excludes individuals known to have<br/>recovered (%g) or died (%g).</small></i>", 
                                       reactive_db()$country, reactive_db()$active_cases, reactive_db()$activeper100k, 
                                       reactive_db()$recovered, reactive_db()$deaths) %>% 
                       lapply(htmltools::HTML),
                       labelOptions = labelOptions(
                                                    style = list("font-weight" = "normal", padding = "3px 8px", "color" = cv19_color),
                                                    textsize = "15px", 
                                                    direction = "auto"))  %>%
      
      addCircleMarkers(data = sars_final, 
                       lat = ~ latitude, 
                       lng = ~ longitude, 
                       weight = 1, 
                       radius = ~(cases)^(1/4), 
                       fillOpacity = 0.2, 
                       color = sars_color, 
                       group = "2003-SARS",
                       label = sprintf("<strong>%s</strong><br/>SARS cases: %g<br/>Deaths: %d<br/>Cases per 100,000: %g", 
                                       sars_final$country, sars_final$cases, sars_final$deaths, sars_final$per100k) %>% 
                       lapply(htmltools::HTML),
                       labelOptions = labelOptions(
                                                    style = list("font-weight" = "normal", padding = "3px 8px", "color" = sars_color),
                                                    textsize = "15px", 
                                                    direction = "auto")) %>%
      
      addCircleMarkers(data = h1n1_cases, 
                       lat = ~ latitude, 
                       lng = ~ longitude, 
                       weight = 1, 
                       radius = ~(projected_deaths)^(1/4), 
                       fillOpacity = 0.2, 
                       color = h1n1_color, 
                       group = "2009-H1N1 (swine flu)",
                       label = sprintf("<strong>%s</strong><br/>H1N1 deaths (confirmed): %g<br/>H1N1 deaths (estimated): %g", 
                                       h1n1_cases$region, h1n1_cases$deaths, h1n1_cases$projected_deaths) %>% 
                       lapply(htmltools::HTML),
                       labelOptions = labelOptions(
                                                    style = list("font-weight" = "normal", padding = "3px 8px", "color" = h1n1_color),
                                                    textsize = "15px", 
                                                    direction = "auto")) %>%
      
      addCircleMarkers(data = ebola_cases, 
                       lat = ~ latitude, 
                       lng = ~ longitude, 
                       weight = 1, 
                       radius = ~(cases)^(1/4), 
                       fillOpacity = 0.2, 
                       color = ebola_color, 
                       group = "2014-Ebola",
                       label = sprintf("<strong>%s</strong><br/>Ebola cases: %g<br/>Deaths: %d", ebola_cases$country, 
                                       ebola_cases$cases, ebola_cases$deaths) %>% 
                       lapply(htmltools::HTML),
                       labelOptions = labelOptions(
                                                    style = list("font-weight" = "normal", padding = "3px 8px", "color" = ebola_color),
                                                    textsize = "15px", 
                                                    direction = "auto"))
  })
  
  output$cumulative_plot <- renderPlot({
    cumulative_plot(covid19_aggregated, input$plot_date)
  })
  
  output$epi_curve <- renderPlot({
    new_cases_plot(covid19_aggregated, input$plot_date)
  })
  
  # sars tab 
  sars_mod_date = reactive({
    format(as.Date(input$sars_plot_date, format="%d %b %y"), "%Y-%m-%d")
  })
  
  output$sars_clean_date_reactive <- renderText({
    format(as.POSIXct(sars_mod_date()),"%d %B %Y")
  })
  
  sars_reactive_db = reactive({
    sars_cases %>% filter(date == sars_mod_date())
  })
  
  sars_reactive_db_large = reactive({
    large_countries = sars_reactive_db() %>% 
      filter(country!="Singapore" & country!="Diamond Princess Cruise Ship" & country!="Hong Kong" & country!="Macao")
    large_countries = large_countries[order(large_countries$alpha3),]
    large_countries
  })
  
  sars_reactive_polygons = reactive({
    worldcountry[worldcountry$id %in% sars_reactive_db_large()$alpha3, ]
  })
  
  output$sars_reactive_case_count <- renderText({
    paste0(sum(sars_reactive_db()$cases), " cases")
  })
  
  output$sars_reactive_death_count <- renderText({
    paste0(sum(sars_reactive_db()$death), " deaths")
  })
  
  
  output$sars_reactive_country_count <- renderText({
    paste0(length(unique(sars_reactive_db()$country_group)), " countries/territories affected")
  })
  
  output$sars_map <- renderLeaflet({
    sars_basemap
  })
  
  observeEvent(input$sars_plot_date, {
    leafletProxy("sars_map") %>% 
      clearMarkers() %>%
      clearShapes() %>%
      addPolygons(data = sars_reactive_polygons(), 
                  stroke = FALSE, 
                  smoothFactor = 0.2, 
                  fillOpacity = 0.1, 
                  fillColor = ~sars_pal(sars_reactive_db_large()$per100k), 
                  group = "2003-SARS (cumulative)",
                  label = sprintf("<strong>%s</strong><br/>SARS cases: %g<br/>Deaths: %d<br/>Cases per 100,000: %g", sars_reactive_db_large()$country, 
                                  sars_reactive_db_large()$cases, sars_reactive_db_large()$deaths, 
                                  sars_reactive_db_large()$per100k) %>% 
                  lapply(htmltools::HTML),
                  labelOptions = labelOptions(
                                                style = list("font-weight" = "normal", padding = "3px 8px", "color" = sars_color),
                                                textsize = "15px", 
                                                direction = "auto")) %>%
      
      addCircleMarkers(data = sars_reactive_db(), 
                       lat = ~ latitude, 
                       lng = ~ longitude, 
                       weight = 1, 
                       radius = ~(cases)^(1/4), 
                       fillOpacity = 0.2, 
                       color = sars_color, 
                       group = "2003-SARS (cumulative)",
                       label = sprintf("<strong>%s</strong><br/>SARS cases: %g<br/>Deaths: %d<br/>Cases per 100,000: %g",  sars_reactive_db()$country, sars_reactive_db()$cases, sars_reactive_db()$deaths, sars_reactive_db()$per100k) %>% 
                       lapply(htmltools::HTML),
                       labelOptions = labelOptions(
                                                    style = list("font-weight" = "normal", padding = "3px 8px", "color" = sars_color),
                                                    textsize = "15px", 
                                                    direction = "auto")) %>%
      
      addCircleMarkers(data = covid19_today, 
                       lat = ~ latitude, 
                       lng = ~ longitude, 
                       weight = 1, 
                       radius = ~(cases)^(1/5),
                       fillOpacity = 0.1, 
                       color = cv19_color, 
                       group = "2019-COVID",
                       label = sprintf("<strong>%s (cumulative)</strong><br/>Confirmed cases: %g<br/>Deaths: %d<br/>Recovered: %d<br/>Cases per 100,000: %g", covid19_today$country, covid19_today$cases, covid19_today$deaths, covid19_today$recovered, covid19_today$per100k) %>% 
                       lapply(htmltools::HTML),
                       labelOptions = labelOptions(
                                                    style = list("font-weight" = "normal", padding = "3px 8px", "color" = cv19_color),
                                                    textsize = "15px", 
                                                    direction = "auto"))  %>%
      
      addCircleMarkers(data = h1n1_cases, 
                       lat = ~ latitude, 
                       lng = ~ longitude, 
                       weight = 1, 
                       radius = ~(projected_deaths)^(1/4),
                       fillOpacity = 0.2, 
                       color = h1n1_color, 
                       group = "2009-H1N1 (swine flu)",
                       label = sprintf("<strong>%s</strong><br/>H1N1 deaths (confirmed): %g<br/>H1N1 deaths (estimated): %g", 
                                       h1n1_cases$region, h1n1_cases$deaths, h1n1_cases$projected_deaths) %>% 
                       lapply(htmltools::HTML),
                       labelOptions = labelOptions(
                                                    style = list("font-weight" = "normal", padding = "3px 8px", "color" = h1n1_color),
                                                    textsize = "15px", 
                                                    direction = "auto")) %>%
      
      addCircleMarkers(data = ebola_cases, 
                       lat = ~ latitude, 
                       lng = ~ longitude, 
                       weight = 1, 
                       radius = ~(cases)^(1/4),
                       fillOpacity = 0.2, 
                       color = ebola_color, 
                       group = "2014-Ebola",
                       label = sprintf("<strong>%s</strong><br/>Ebola cases: %g<br/>Deaths: %d", 
                                       ebola_cases$country, ebola_cases$cases, ebola_cases$deaths) %>% 
                       lapply(htmltools::HTML),
                       labelOptions = labelOptions(
                                                    style = list("font-weight" = "normal", padding = "3px 8px", "color" = ebola_color),
                                                    textsize = "15px", 
                                                    direction = "auto")) 
  })
  
  output$sars_cumulative_plot <- renderPlot({
    sars_cumulative_plot(sars_aggregated, sars_mod_date())
  })
  
  output$sars_epi_curve <- renderPlot({
    sars_new_cases_plot(sars_aggregated, sars_mod_date())
  })
  
  # comparison plot
  output$comparison_plot <- renderPlotly({
    comparison_plot(epi_comp, input$comparison_metric)
  })
  
  # add footnote for cases
  output$epi_notes_1 <- renderText({
    if(input$comparison_metric=="cases") { 
      paste0("Note that the axis is on a log10 scale so moves in 10-fold increments.The 60.8 million estimated cases of H1N1 dwarf all other outbreaks of plotted on a standard linear scale.") 
    }
  })
  
  # add footnote for deaths
  output$epi_notes_2 <- renderText({
    if(input$comparison_metric=="deaths") { 
      paste0("For H1N1, the number of laboratory-confirmed deaths reported by the WHO is displayed. Subsequent modelling studies have estimated the actual number to be in the range of 123,000 to 203,000.")
    }
  })
  
  # add note for cfr
  output$epi_notes_3 <- renderText({
    if(input$comparison_metric=="cfr") { 
      paste0("For COVID-19, this displays the proportion of confirmed cases who have subsequently died. When factoring in mild or asymptomatic infections that are not picked up by case surveillance efforts, current estimates place the case fatality rate in the range of 0.3-1%.")
    }
  })
  
  # update region selections
  observeEvent(input$level_select, {
    if (input$level_select=="Global") {
      updatePickerInput(session = session, inputId = "region_select", 
                        choices = "Global", selected = "Global")
    }
    
    if (input$level_select=="Continent") {
      updatePickerInput(session = session, inputId = "region_select", 
                        choices = c("Africa", "Asia", "Europe", "North America", "South America"), 
                        selected = c("Africa", "Asia", "Europe", "North America", "South America"))
    }
    
    if (input$level_select=="Country") {
      updatePickerInput(session = session, inputId = "region_select", 
                        choices = as.character(cv_today_100[order(-cv_today_100$cases),]$country), 
                        selected = cv_today_100$country)
    }
  }, ignoreInit = TRUE)
  
  # create dataframe with selected countries
  country_reactive_db = reactive({
    if (input$level_select=="Global") { 
      db = cv_cases_global
      db$region = db$global_level
    }
    if (input$level_select=="Continent") { 
      db = cv_cases_continent 
      db$region = db$continent
    }
    if (input$level_select=="Country") { 
      db = covid19_cases
      db$region = db$country
    }
    
    if (input$outcome_select=="Cases") { 
      db$outcome = db$cases
      db$new_outcome = db$new_cases
    }
    
    if (input$outcome_select=="Deaths") { 
      db$outcome = db$deaths 
      db$new_outcome = db$new_deaths 
    }
    
    if (input$outcome_select=="Recovered") { 
      db$outcome = db$recovered 
      db$new_outcome = db$new_recovered 
    }
    
    db %>% filter(region %in% input$region_select)
  })
  
  
  
  
  # country-specific plots
  output$country_plot <- renderPlotly({
    country_region_cases_plot(country_reactive_db(), start_point=input$start_date)
  })
  
  # country-specific plots
  output$country_plot_cumulative <- renderPlotly({
    country_region_cases_cumulative(country_reactive_db(), start_point=input$start_date)
  })
  
  # country-specific plots
  output$country_plot_cumulative_log <- renderPlotly({
    country_region_cases_cumulative_log(country_reactive_db(), start_point=input$start_date)
  })
  
  # output to download data
  output$downloadCsv <- downloadHandler(
    filename = function() {
      paste("COVID_data_", covid19_today$date[1], ".csv", sep="")
    },
    content = function(file) {
      write.csv(covid19_cases %>% select(c(country, date, cases, new_cases, deaths, new_deaths,
                                       recovered, new_recovered, active_cases, 
                                       per100k, newper100k, activeper100k)), file)
    }
  )
  
  output$rawtable <- renderTable({ print(tail(cv_rawtable, input$maxrows), row.names = FALSE) })
  
  us_states_reactive_db = reactive({
    covid19_us_states
  })
  
  observeEvent(input$us_plot_start_date, {
    usastates_plot(covid19_us_states, input$us_plot_start_date, input$us_state_outcome_select)
  })
  observeEvent(input$us_state_outcome_select, {
    usastates_plot(covid19_us_states, input$us_plot_start_date, input$us_state_outcome_select)
  })
  
  output$usastates_plot <- renderPlot({
    usastates_plot(us_states_reactive_db(), input$us_plot_start_date, input$us_state_outcome_select)
  })
  
  us_states_reactive_db2 = reactive({
    covid19_us_states
  })
  
  observeEvent(input$us_plot_start_date2, {
    usastates_plot2(covid19_us_states, input$us_plot_start_date2, input$us_state_outcome_select2)
  })
  observeEvent(input$us_state_outcome_select2, {
    usastates_plot2(covid19_us_states, input$us_plot_start_date2, input$us_state_outcome_select2)
  })
  
  output$usastates_plot2 <- renderLeaflet({
    usastates_plot2(us_states_reactive_db2(), input$us_plot_start_date2, input$us_state_outcome_select2)
  })
}

runApp(shinyApp(ui, server), launch.browser = TRUE)
#shinyApp(ui, server)
```
