---
title: "covid19_source"
author: "Viren Patel"
date: "4/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
# load libraries
if(!require(stringr)) install.packages("stringr", repos = "http://cran.us.r-project.org")
if(!require(stringi)) install.packages("stringi", repos = "http://cran.us.r-project.org")
if(!require(dplyr)) install.packages("dplyr", repos = "http://cran.us.r-project.org")
```

```{r functions}
update = function(input_df, tag) {
  names(input_df)[1:2] = c("Province", "Country")
  input_df$Country[input_df$Province=="Hong Kong"] = "Hong Kong"
  input_df$Country[input_df$Province=="Macau"] = "Macao"
  input_df$Country[input_df$Country=="Taiwan*"] = "Taiwan"
  input_df$Country[input_df$Country=="Korea, South"] = "RepublicofKorea"
  input_df$Country[input_df$Country=="Congo (Brazzaville)" | input_df$Country=="Republic of the Congo"] = "Congo"
  input_df$Country[input_df$Country=="Congo (Kinshasa)"] = "Democratic Republic of the Congo"
  input_df$Country[input_df$Country=="Cote d'Ivoire"] = "CotedIvoire"
  input_df$Country[input_df$Country=="Gambia, The"] = "TheGambia"
  input_df$Country[input_df$Country=="Bahamas, The"] = "TheBahamas"
  input_df$Country[input_df$Country=="Cabo Verde"] = "CapeVerde"
  input_df$Country[input_df$Country=="Timor-Leste"] = "TimorLeste"
  input_df$Country[input_df$Country=="Guinea-Bissau"] = "GuineaBissau"
  input_df$Country = input_df$Country %>% str_replace_all(., " ", "") 
  dates = names(input_df)[which(names(input_df)=="1/22/20"):ncol(input_df)]
  input_df = input_df %>% 
    select(-c(Province, Lat, Long)) %>% 
    group_by(Country) %>% 
    summarise_each(funs(sum)) %>%
    data.frame()
  rownames(input_df) = input_df$Country
  rownames(input_df) = paste0(input_df$Country,"_",tag)
  input_df = input_df %>% select(-c(Country)) %>% t()
  input_df = data.frame(input_df)
  input_df$Date = dates
  rownames(input_df) = 1:nrow(input_df)
  input_df$Date = format(as.Date(input_df$Date,"%m/%d/%y"))
  input_df
}
```

```{r process}
# load latest Covid-2019 data: confirmed cases
covid19_cases <- as.data.frame(data.table::fread("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"))
covid19_cases[is.na(covid19_cases)]=0
total_cases <- sum(covid19_cases[,ncol(covid19_cases)])
covid19_cases = update(covid19_cases, "cases")
if (total_cases!=sum(covid19_cases[nrow(covid19_cases),1:(ncol(covid19_cases)-1)])) { stop(paste0("Error: incorrect processing - total counts do not match")) }

# load latest Covid-2019 data: deaths
covid19_deaths <- as.data.frame(data.table::fread("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"))
covid19_deaths[is.na(covid19_deaths)]=0
total_deaths <- sum(covid19_deaths[,ncol(covid19_deaths)])
covid19_deaths = update(covid19_deaths, "deaths")
if (total_deaths!=sum(covid19_deaths[nrow(covid19_deaths),1:(ncol(covid19_deaths)-1)])) { stop(paste0("Error: incorrect processing - total counts do not match")) }

# load latest Covid-2019 data: recovered
covid19_rec <- as.data.frame(data.table::fread("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv"))
covid19_rec[is.na(covid19_rec)]=0
total_rec <- sum(covid19_rec[,ncol(covid19_rec)])
covid19_rec = update(covid19_rec, "recovered")
if (total_rec!=sum(covid19_rec[nrow(covid19_rec),1:(ncol(covid19_rec)-1)])) { stop(paste0("Error: incorrect processing - total counts do not match")) }

# merge dataframes 
covid19_merge = merge(covid19_cases, covid19_deaths, by = "Date")
covid19_merge = merge(covid19_merge, covid19_rec, by = "Date")
covid19_merge$Date = as.Date(covid19_merge$Date, format="%Y-%m-%d")
covid19_merge$update = 1:nrow(covid19_merge)
write.csv(covid19_merge, "source/jhu_data.csv")

# load country data
countries = read.csv("source/countries_codes_and_coordinates.csv")

# check all jhu country names have corresponding country data
covid19_country_list = names(covid19_merge)[grepl("_cases", names(covid19_merge))] %>% str_replace_all(., "_cases", "") 
if (all(covid19_country_list %in% countries$jhu_ID)==FALSE) {
  stop(paste0("Error: mapping data lacking for the following countries: ",covid19_country_list[(covid19_country_list %in% countries$jhu_ID)==FALSE]))
}

collated_data = NULL
# loop to add new data for each new situation report
for (i in c(1:nrow(covid19_merge))) {
  
  # extract subset of data for date in row i
  covid19_subset = covid19_merge[i,]
  covid19_subset_cases = covid19_subset[,which(grepl("_cases", names(covid19_subset)))]
  covid19_subset_cases = covid19_subset_cases[,colSums(covid19_subset_cases)>0]
  covid19_subset_deaths = covid19_subset[,which(grepl("_deaths", names(covid19_subset)))]
  covid19_subset_rec = covid19_subset[,which(grepl("_recovered", names(covid19_subset)))]
  
  # build new dataframe to add updated data
  new_data = data.frame(jhu_ID = names(covid19_subset_cases) %>% str_replace_all(., "_cases", ""),
                        date = format(as.Date(covid19_subset$Date[1],"%Y-%m-%d")),
                        update = i,
                        cases = NA, new_cases = 0,
                        deaths = 0, new_deaths = 0,
                        recovered = 0, new_recovered = 0)
  
  # update column names in new_jhu dataframes to include country names only
  colnames(covid19_subset_cases) = colnames(covid19_subset_cases) %>% str_replace_all(., "_cases", "") 
  colnames(covid19_subset_deaths) = colnames(covid19_subset_deaths) %>% str_replace_all(., "_deaths", "") 
  colnames(covid19_subset_rec) = colnames(covid19_subset_rec) %>% str_replace_all(., "_recovered", "")
  
  # loop to update cases
  for (j in 1:nrow(new_data)) {
    # update case numbers
    country_name = as.character(new_data$jhu_ID[j])
    new_data$cases[j] = covid19_subset_cases[,country_name]
    new_data$deaths[j] = covid19_subset_deaths[,country_name]
    new_data$recovered[j] = covid19_subset_rec[,country_name]
  }
  
  # append new data to collated dataframe
  collated_data = rbind(collated_data, new_data)
  collated_data$jhu_ID = as.character(collated_data$jhu_ID)
  
  # calculate new cases, deaths and recoveries
  if (i == 1) {
    collated_data$new_cases = collated_data$cases
    collated_data$new_deaths = collated_data$deaths
    collated_data$new_recovered = collated_data$recovered
  }
  
  if (i > 1) {
    # split it into date i and date i-1
    today = subset(collated_data, update==i)
    yesterday = subset(collated_data, update==(i-1))
    
    for (k in 1:nrow(today)) {
      country_name = today$jhu_ID[k]
      
      # if present in yesterday's data, calculate new cases by subtraction
      if (country_name %in% yesterday$jhu_ID) {
        collated_data$new_cases[collated_data$jhu_ID==country_name & collated_data$update==i] = today$cases[today$jhu_ID==country_name] - yesterday$cases[yesterday$jhu_ID==country_name] 
        collated_data$new_deaths[collated_data$jhu_ID==country_name & collated_data$update==i] = today$deaths[today$jhu_ID==country_name] - yesterday$deaths[yesterday$jhu_ID==country_name] 
        collated_data$new_recovered[collated_data$jhu_ID==country_name & collated_data$update==i] = today$recovered[today$jhu_ID==country_name] - yesterday$recovered[yesterday$jhu_ID==country_name] 
      } else {
        # if absent from yesterday's data, new observations = total observations
        collated_data$new_cases[collated_data$jhu_ID==country_name & collated_data$update==i] = today$cases[today$jhu_ID==country_name] 
        collated_data$new_deaths[collated_data$jhu_ID==country_name & collated_data$update==i] = today$deaths[today$jhu_ID==country_name]  
        collated_data$new_recovered[collated_data$jhu_ID==country_name & collated_data$update==i] = today$recovered[today$jhu_ID==country_name] 
      }
    }
  }
}
# allow for repatriation or reassigned cases without negative new_cases, new_deaths and new_recovered counts
collated_data$new_cases[collated_data$new_cases<0] = 0
collated_data$new_deaths[collated_data$new_deaths<0] = 0
collated_data$new_recovered[collated_data$new_recovered<0] = 0

# add active case data (total cases - deaths/recovered)
collated_data$active_cases = collated_data$cases - (collated_data$deaths + collated_data$recovered)

# update country names
collated_data = merge(collated_data, countries[,c("jhu_ID", "country")], by = "jhu_ID")

# re-order
collated_data = collated_data[order(as.Date(collated_data$date, format="%Y-%m-%d"), -collated_data$cases, collated_data$country),]

# update time stamp
collated_data$last_update = NA
collated_data$last_update[nrow(collated_data)] = paste(format(as.POSIXlt(Sys.time(), "GMT"), "%d %B %H:00"), "GMT")

# save file
write.csv(collated_data, "source/coronavirus.csv", row.names=F)
rm(list = ls())
```
